name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure Git
        run: |
          git config --global user.email "mastercoms@tuta.io"
          git config --global user.name "mastercoms"

      - name: Apply Patches
        run: ./glowkit p

      - name: Maven Build
        run: mvn --batch-mode package -Pbuild-extras
        working-directory: ./Glowkit-Patched
