name: Build and Deploy

on:
  push:
    branches:
      - master
      - "1.16"
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: glowstone-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure Git
        run: |
          git config --global user.email "mastercoms@tuta.io"
          git config --global user.name "mastercoms"

      - name: Apply Patches
        run: ./glowkit p
    
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Build and Deploy
        run: mvn --batch-mode deploy -Pbuild-extras
        working-directory: ./Glowkit-Patched
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
