name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: glowstone-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure Git
        run: |
          git config --global user.email "mastercoms@tuta.io"
          git config --global user.name "mastercoms"

      - name: Apply Patches
        run: ./glowkit p
    
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Maven
        run: mvn -T 1C -B dependency:go-offline
        working-directory: ./Glowkit-Patched

      - name: Maven Build and Deploy
        run: mvn -T 1C -B source:jar javadoc:jar deploy -Pbuild-extras
        working-directory: ./Glowkit-Patched
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Push Javadocs to Pages
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: 'Glowkit-Patched/target/apidocs/.'
          destination_repo: 'GlowstoneMC/glowstonemc.github.io'
          destination_folder: 'content/jd/glowkit/1.16/' # TODO: detect version?
          user_email: 'mastercoms@tuta.io'
          user_name: 'mastercoms'
          commit_message: Update Javadocs for Glowkit commit ${{ github.sha }}
