name: Update Upstream

on:
  workflow_dispatch:
  
jobs:
  upstream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "mastercoms@tuta.io"
          git config --global user.name "mastercoms"

      - name: Update Upstream
        run: ./scripts/upstreamMerge.sh

      - name: Commit Upstream
        run: ./scripts/upstreamCommit.sh

      - name: Push
        run: git push
